# Generated by Django 6.1 on 2026-09-14 14:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicecategory_options_servicecategory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
