# Generated by Django 6.1 on 2026-09-28 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_wallettransaction_wallet_and_more'),
        ('projects', '0003_order_orderinspiration_orderlineitem_orderstatuslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, help_text="When the escrow funds were released to the provider's wallet.", null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_escrow_held',
            field=models.BooleanField(default=False, help_text='Money is in escrow — waiting for client approval before release.'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.order'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-PESA'), ('airtel_money', 'Airtel Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet Balance'), ('internal', 'Internal Ledger')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Project Deposit'), ('final', 'Project Final Payment'), ('order_deposit', 'Order Deposit'), ('order_balance', 'Order Balance Payment'), ('order_release', 'Order Balance Released to Fundi'), ('refund', 'Refund'), ('payout', 'Payout to Provider'), ('withdrawal', 'Provider Withdrawal'), ('wallet_deposit', 'Wallet Deposit')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_3a2ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_3e0999_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'payment_type'], name='payments_pa_status_594e38_idx'),
        ),
    ]
