# Generated by Django 6.1 on 2026-09-28 11:26

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_dispute_attachment_alter_projectdocument_file_and_more'),
        ('services', '0005_servicecategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What the client wants done.')),
                ('materials_mode', models.CharField(choices=[('fundi_provides', 'Fundi provides materials'), ('client_provides', 'Client provides materials'), ('no_materials', 'No materials required')], default='fundi_provides', max_length=20)),
                ('materials_notes', models.TextField(blank=True, help_text='Details about the materials — types, quantity, condition.', null=True)),
                ('estimated_days', models.IntegerField(blank=True, help_text="Fundi's estimate of how long the job will take.", null=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='The labour price agreed between client and fundi.', max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='10% commission — deducted from fundi payout.', max_digits=12)),
                ('escrow_service_fee', models.DecimalField(decimal_places=2, default=0, help_text='3% customer-side escrow fee — added to invoice.', max_digits=12)),
                ('customer_total', models.DecimalField(decimal_places=2, default=0, help_text='agreed_price + escrow_service_fee.', max_digits=12)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=30, help_text='Deposit percentage (default 30%).', max_digits=5)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Deposit = deposit_percent% of customer_total.', max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, help_text='customer_total - deposit_amount.', max_digits=12)),
                ('provider_payout', models.DecimalField(decimal_places=2, default=0, help_text='agreed_price - platform_fee.', max_digits=12)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('balance_paid', models.BooleanField(default=False)),
                ('balance_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_paid_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_requested_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_acceptance', 'Pending Fundi Acceptance'), ('accepted', 'Accepted — Awaiting Deposit'), ('deposit_paid', 'Deposit Paid — Ready to Start'), ('in_progress', 'In Progress'), ('milestone_ready', 'View / Fit Available'), ('submitted', 'Work Submitted — Awaiting Approval'), ('completed', 'Completed'), ('declined', 'Declined by Fundi'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_acceptance', max_length=25)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('disclaimer_accepted', models.BooleanField(default=False, help_text='Client confirmed materials/designs supplied are at their own risk.')),
                ('disclaimer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_provider', to=settings.AUTH_USER_MODEL)),
                ('selected_sample', models.ForeignKey(blank=True, help_text='The portfolio image the client picked as their reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceportfolio')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='projects.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, default='piece', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provided_by', models.CharField(choices=[('fundi', 'Fundi provides'), ('client', 'Client provides')], default='fundi', max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.order')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('note', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='projects.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='projects_or_custome_85d965_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', '-created_at'], name='projects_or_provide_120044_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='projects_or_status_92556f_idx'),
        ),
    ]
