# Generated by Django 6.1 on 2026-09-28 10:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Overall identity verification state for this user.', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Clear face photo. No glasses, hats, or filters.', max_length=255, null=True, verbose_name='face_photo')),
                ('face_photo_verified', models.BooleanField(default=False, help_text='Set by admin after confirming the face matches the ID.')),
                ('id_document', cloudinary.models.CloudinaryField(blank=True, help_text='National ID or passport. Stored privately.', max_length=255, null=True, verbose_name='id_document')),
                ('id_document_verified', models.BooleanField(default=False, help_text='Set by admin after confirming the document is authentic.')),
                ('id_document_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport')], max_length=20, null=True)),
                ('phone_public', models.BooleanField(default=False, help_text="Flips True after the provider's first escrow deposit.")),
                ('sub_county', models.CharField(blank=True, max_length=80, null=True)),
                ('ward', models.CharField(blank=True, max_length=80, null=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest price the provider will accept for a job.', max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Typical upper range for their work.', max_digits=12, null=True)),
                ('business_licence', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_licence')),
                ('business_licence_verified', models.BooleanField(default=False)),
                ('nca_licence', cloudinary.models.CloudinaryField(blank=True, help_text='National Construction Authority licence, if applicable.', max_length=255, null=True, verbose_name='nca_licence')),
                ('nca_licence_verified', models.BooleanField(default=False)),
                ('other_licence', cloudinary.models.CloudinaryField(blank=True, help_text='Any other professional licence (e.g. EPRA, NTSA).', max_length=255, null=True, verbose_name='other_licence')),
                ('other_licence_name', models.CharField(blank=True, max_length=120, null=True)),
                ('other_licence_verified', models.BooleanField(default=False)),
                ('is_verified_provider', models.BooleanField(default=False, help_text='Grants the blue verified tick. Set by admin.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the provider was granted the blue verified tick.', null=True)),
                ('shop_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='shop_photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
            },
        ),
    ]
