# Generated by Django 6.0.7 on 2026-07-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_project_updates', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_project_updates', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_project_updates', models.BooleanField(default=True)),
                ('in_app_messages', models.BooleanField(default=True)),
                ('in_app_payments', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('project', 'Project'), ('message', 'Message'), ('review', 'Review'), ('dispute', 'Dispute'), ('system', 'System'), ('promotion', 'Promotion')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('desktop', 'Desktop App')], max_length=20)),
                ('device_id', models.CharField(max_length=255)),
                ('registration_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
